import { asset } from '../lib/asset.js'
import { PAGE_PATHS } from '../lib/i18n.js'

const Arrow=()=> <span aria-hidden="true">↗</span>
const List=({items})=> <ul className="brief-list">{items.map(x=><li key={x}>{x}</li>)}</ul>
const Title=({over,title})=> {
  const philosophy=['Our philosophy','Nuestra filosofía'].includes(title)
  const image=philosophy?['real_training.jpeg',title==='Nuestra filosofía'?'Jugadores de Respect escuchando atentamente las instrucciones antes del partido':'Respect players listening attentively to pre-match instructions',`${title} · One Team`]:null
  return <><div className="brief-title"><span className="eyebrow">{over}</span><h2>{title}</h2></div>{image&&<figure className="academy-editorial-image"><img src={asset(image[0])} alt={image[1]} loading="lazy"/><figcaption>{image[2]}</figcaption></figure>}</>
}

export default function About({locale}) {
  const es=locale==='es', tx=(en,spanish)=>es?spanish:en
  const home=PAGE_PATHS.home[locale]
  const methodology=tx(['understanding the game;','decision-making;','creating space;','using space;','technical ability;','tactical thinking;','personal development.'],['comprensión del juego;','toma de decisiones;','creación de espacios;','utilización de espacios;','dominio técnico;','pensamiento táctico;','desarrollo personal.'])
  const philosophy=tx(['developing our own players;','modern attacking football;','one unified club playing model;','long-term development;','a strong football identity;','development of football intelligence;','brave and intelligent football;','creating and exploiting space;','developing players capable of making high-level decisions.'],['desarrollo de nuestros jugadores;','fútbol ofensivo moderno;','un único modelo de juego;','desarrollo a largo plazo;','una identidad futbolística fuerte;','desarrollo de la inteligencia futbolística;','fútbol valiente e inteligente;','creación y aprovechamiento de espacios;','jugadores capaces de decidir al más alto nivel.'])
  const goals=tx(['develop our own academy players and build the core from Respect players;','progress through the Spanish football pyramid;','reach national-level competition;','establish a professional club structure;','become one of the most recognisable projects in the Canary Islands;','give players the opportunity to compete at the highest possible level;','create a club that Tenerife can be proud of.'],['desarrollar nuestros jugadores y formar la base con futbolistas Respect;','ascender en la pirámide del fútbol español;','alcanzar competiciones nacionales;','crear una estructura profesional;','ser uno de los proyectos más reconocidos de Canarias;','permitir a los jugadores competir al máximo nivel;','crear un club del que Tenerife pueda sentirse orgulloso.'])
  return <main className="client-brief">
    <section className="section section--offset-nav">
      <div className="section__inner">
        <span className="eyebrow">{tx('ABOUT THE PROJECT','SOBRE EL PROYECTO')}</span>
        <h1>{tx('Our mission, philosophy and vision','Nuestra misión, filosofía y visión')}</h1>
        <p className="hero-project__intro">{tx('The thinking behind Respect Football Project: why we exist, how we work and where we want to take the club.','La idea detrás de Respect Football Project: por qué existimos, cómo trabajamos y hacia dónde queremos llevar el club.')}</p>
        <a className="btn btn--outline" href={home}>{tx('← Back to home','← Volver al inicio')}</a>
      </div>
    </section>
    <section className="section section--cream" id="about"><div className="section__inner brief-two-col"><div><Title over={tx('ABOUT THE PROJECT','SOBRE EL PROYECTO')} title={tx('Respect Football Project was founded in 2023 on the island of Tenerife, Spain.','Respect Football Project fue fundado en 2023 en la isla de Tenerife, España.')}/><p className="large-copy">{tx('Our mission is to create a complete football development system that combines education, player development, competitive experience and real career opportunities.','Nuestra misión es crear un sistema completo de formación de futbolistas que combine educación, desarrollo, experiencia competitiva y oportunidades profesionales reales.')}</p><p>{tx('We believe that modern football requires more than technical ability and physical qualities.','Creemos que el fútbol moderno requiere más que técnica y cualidades físicas.')}</p><h3 className="gold-statement">{tx('The most important quality of a footballer is football intelligence.','La cualidad más importante de un futbolista es la inteligencia futbolística.')}</h3></div><div className="brief-panel"><p>{tx('Our methodology is based on:','Nuestra metodología se basa en:')}</p><List items={methodology}/></div></div><div className="section__inner full-quote">{tx('We do not build teams for one season. We build players for an entire career.','No construimos equipos para una temporada. Construimos jugadores para toda una carrera.')}</div></section>
    <section className="section philosophy-section"><div className="section__inner"><Title over="SENIOR TEAM" title={tx('Our philosophy','Nuestra filosofía')}/><div className="principle-grid">{philosophy.map(x=><div key={x}><p>{x}</p></div>)}</div><div className="brief-manifesto"><h3>{tx('Football does not begin with physical qualities. It begins with understanding the game.','El fútbol no comienza con las cualidades físicas, sino con la comprensión del juego.')}</h3><p>{tx('We develop players who can think, analyse, make decisions and control the game.','Desarrollamos jugadores capaces de pensar, analizar, decidir y controlar el juego.')}</p></div></div></section>
    <section className="section section--cream"><div className="section__inner brief-two-col"><div><Title over="SENIOR TEAM" title={tx('Our objectives','Nuestros objetivos')}/><p className="large-copy">{tx('Respect Senior Team is being built as a long-term sporting project with major ambitions.','Respect Senior Team se construye como un proyecto deportivo a largo plazo con grandes ambiciones.')}</p></div><div className="brief-panel brief-panel--light"><List items={goals}/></div></div></section>
    <section className="editorial vision"><img src={asset('respect_1.webp')} alt="Respect team" loading="lazy"/><div className="editorial__shade"/><div className="editorial__copy"><span className="eyebrow">{tx('Our vision','Nuestra visión')}</span><h2>{tx('We believe major achievements begin with major goals.','Creemos que los grandes logros comienzan con grandes objetivos.')}</h2><p>{tx('Today we are building the foundation. Tomorrow we want to see Respect among strong clubs in Spain.','Hoy construimos los cimientos. Mañana queremos ver a Respect entre los clubes fuertes de España.')}</p><p>{tx('Every major club once began with one pitch, one team and people who believed in an idea. Respect is being built with a long-term vision and without limits on its ambition.','Todo gran club comenzó con un campo, un equipo y personas que creyeron en una idea. Respect se construye con visión a largo plazo y sin límites para su ambición.')}</p><p>{tx('Our dream is to take Respect into professional football, compete against the best and represent Tenerife in Spain and Europe.','Nuestro sueño es llevar a Respect al fútbol profesional, competir contra los mejores y representar a Tenerife en España y Europa.')}</p></div></section>
    <section className="section about-return"><div className="section__inner"><a className="btn btn--gold" href={home}>{tx('Back to home','Volver al inicio')} <Arrow/></a></div></section>
  </main>
}
